apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudstorage-config
  namespace: cloudstorage
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis-cluster"
